### PR TITLE
Change the path and filename to not conflict with addon

### PR DESCRIPTION
**Pull request by alias-mac**
While swapping the project to use yarn, some of our dependencies are using this package and `ember build` started creating `dist/assets/vendor.js` with the `index.js` file of this package instead of the file defined by the `this.import()` line:
https://github.com/rwjblue/ember-factory-for-polyfill/blob/master/index.js#L18

While debugging this, I noticed that the problem is that when we swapped to yarn both files exist in the folder that broccoli uses to merge:
`ember-factory-for-polyfill/index.js`
`ember-factory-for-polyfill/vendor/ember-factory-for-polyfill/index.js`
So both get included even tho the `ember-factory-for-polyfill/index.js` one is a link (see screenshot attached).

screen shot 2017-04-28 at 20 05 12

I'm pretty sure that this is caused by the fact that yarn has different package paths for `node_modules` than NPM, and thus creating this problem only for projects using yarn and with some particular configuration.

Please let me know if you need more information about this fix.

### CODE REVIEW

**Comment by rwjblue** [comment]
Something in your build is exposing all of mode_modules into vendor (this is not good 😱). I'm not opposed to changing the file name but you should really track down that other bug.

**Comment by alias-mac** [comment]
I'll try to see if other similar projects using yarn have the same behavior, and if not, I'll try to find which module is causing this on our project.
At least with this fix, we would be unblocked to swap to yarn which makes our full build times much faster.

**Comment by rwjblue** [comment]
I have many projects using yarn that do not exhibit this behavior.  

If we are going to change the name, I'd prefer to keep it in the `ember-factory-for-polyfill` subfolder.  Can you update this PR to move the file to `vendor/ember-factory-for-polyfill/polyfill.js` instead?

**Comment by alias-mac** [comment]
Ok, I was just trying to follow the same format used in https://github.com/rwjblue/ember-getowner-polyfill/blob/master/index.js#L18

I updated and tested it locally and seems to still work fine, since it won't conflict with the `index.js`.

Updated the PR. Let me know if you need anything else and I'll keep you posted on what I find about what is causing the other files to be linked to the `tmp` folder.

**Comment by alias-mac** [comment]
@rwjblue, I did a bit more digging with one of our biggest projects and I got the same result (they aren't using this package but one of the dependencies is using `ember-getowner-polyfill`).

Here is what I found:
```
tmp//broccoli_merge_trees-input_base_path-Bv4fQpLF.tmp/0/modules/ember-getowner-polyfill/index.js
tmp//broccoli_merge_trees-input_base_path-kWgllJ4N.tmp/1/modules/ember-getowner-polyfill/index.js
tmp//broccoli_merge_trees-input_base_path-lOVJ9XGK.tmp/0/modules/ember-getowner-polyfill/index.js
tmp//broccoli_merge_trees-input_base_path-rVVa4Qjb.tmp/37/modules/ember-getowner-polyfill/index.js
tmp//broccoli_merge_trees-input_base_path-WzbluZgy.tmp/0/modules/ember-getowner-polyfill/index.js
//... other similar stuff
tmp//rollup-cache_path-UBSgWWwb.tmp/node_modules/ember-getowner-polyfill/index.js
tmp//simple_concat_concat-input_base_path-Qbs7J7l3.tmp/ember-getowner-polyfill/index.js
tmp//simple_concat_concat-input_base_path-r8bG4AXD.tmp/modules/ember-getowner-polyfill/index.js
tmp//source_map_concat-input_base_path-3JSXrO6t.tmp/modules/ember-getowner-polyfill/index.js
tmp//source_map_concat-input_base_path-JxYYNmSI.tmp/modules/ember-getowner-polyfill/index.js
tmp//source_map_concat-input_base_path-KtFVtlht.tmp/modules/ember-getowner-polyfill/index.js
tmp//source_map_concat-input_base_path-nc7AOAqV.tmp/modules/ember-getowner-polyfill/index.js
tmp//source_map_concat-input_base_path-WYj25bKR.tmp/modules/ember-getowner-polyfill/index.js
```

It seems that the original module is always copied into the temporary folders for broccoli, rollup, concat and source maps.

I wasn't able to track which package copies the files into the `tmp` folder, since it seems that it isn't using any of nodejs' `fs.*` functions to copy the files.

If you can point me in the right direction, maybe I can find which part of the build in ember-cli is not working as expected.

**Pull request closed without merging**
